# Generated by Django 4.2.18 on 2025-02-13 23:08

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractorprofile',
            name='locations',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('ascot', 'Ascot'), ('bracknell', 'Bracknell'), ('crowthorne', 'Crowthorne'), ('earley', 'Earley'), ('eton', 'Eton'), ('hungerford', 'Hungerford'), ('maidenhead', 'Maidenhead'), ('newbury', 'Newbury'), ('reading', 'Reading'), ('sandhurst', 'Sandhurst'), ('slough', 'Slough'), ('thatcham', 'Thatcham'), ('windsor', 'Windsor'), ('wokingham', 'Wokingham'), ('woodley', 'Woodley')], max_length=100), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='contractorprofile',
            name='skills',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('carpentry', 'Carpentry'), ('plumbing', 'Plumbing'), ('electrical', 'Electrical'), ('masonry', 'Masonry'), ('hvac', 'HVAC'), ('painting', 'Painting and decorating'), ('roofing', 'Roofing'), ('landscaping', 'Landscaping'), ('tiling', 'Tiling'), ('drywall', 'Drywall installation and finishing'), ('insulation', 'Insulation'), ('flooring', 'Flooring')], max_length=100), blank=True, null=True, size=None),
        ),
    ]
