# Generated by Django 4.2.18 on 2025-02-13 23:29

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractor', '0002_alter_contractorprofile_locations_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractorprofile',
            name='availability',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DateField(), blank=True, null=True, size=None),
        ),
    ]
