# Generated by Django 4.2.18 on 2025-02-14 14:46

import cloudinary.models
from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contractor', '0003_alter_contractorprofile_availability'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_contractor', models.BooleanField(default=False)),
                ('profile_image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('skills', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('carpentry', 'Carpentry'), ('plumbing', 'Plumbing'), ('electrical', 'Electrical'), ('masonry', 'Masonry'), ('hvac', 'HVAC'), ('painting', 'Painting and decorating'), ('roofing', 'Roofing'), ('landscaping', 'Landscaping'), ('tiling', 'Tiling'), ('drywall', 'Drywall installation and finishing'), ('insulation', 'Insulation'), ('flooring', 'Flooring')], max_length=100), blank=True, null=True, size=None)),
                ('locations', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('ascot', 'Ascot'), ('bracknell', 'Bracknell'), ('crowthorne', 'Crowthorne'), ('earley', 'Earley'), ('eton', 'Eton'), ('hungerford', 'Hungerford'), ('maidenhead', 'Maidenhead'), ('newbury', 'Newbury'), ('reading', 'Reading'), ('sandhurst', 'Sandhurst'), ('slough', 'Slough'), ('thatcham', 'Thatcham'), ('windsor', 'Windsor'), ('wokingham', 'Wokingham'), ('woodley', 'Woodley')], max_length=100), blank=True, null=True, size=None)),
                ('availability', django.contrib.postgres.fields.ArrayField(base_field=models.DateField(), blank=True, null=True, size=None)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='ContractorProfile',
        ),
    ]
