# Generated by Django 4.2.18 on 2025-02-15 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractor', '0007_alter_contractorrating_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractorrating',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
