# Generated by Django 4.2.18 on 2025-02-16 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contractor', '0008_contractorrating_approved'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contractorrating',
            old_name='content',
            new_name='review',
        ),
    ]
